### PR TITLE
Housekeeping - bringing things up to date and cleaning up build

### PR DESCRIPTION
**Pull request by hazendaz**
Lots of various things to bring build up to date.  Nothing new in the lines of providing something cool to the library.  See commit history.

### CODE REVIEW

**Comment by hazendaz** [comment]
@robert-bor Any status on this PR?

**Comment by hazendaz** [comment]
@robert-bor Any status on this PR?

**Comment by hazendaz** [comment]
I have rebased this against current master.  Is it possible this can get merged?

**Comment by hazendaz** [comment]
@robert-bor many pull requests / many issues starting to back up.  Are you engaged here?  I've had this open for almost 2 years.  I'm more than willing to join the team and get this moving.  I'll give it a bit longer but if I don't hear anything back I'm going to move foward with forking off and trying to address my build hiegine and others bug needs.

**Comment by robert-bor** [comment]
Hi Jeremy, see email. Would love to have you aboard.

**Pull request merged**
